; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qspi
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
monitor_speed = 115200
monitor_port = /dev/ttyACM0

; Upload Configs for OTA
; upload_port = /dev/ttyACM0
upload_port = 10.53.227.126
upload_protocol = espota

board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
lib_deps = 
	adafruit/Adafruit Unified Sensor@^1.1.14
	adafruit/Adafruit BNO08x@^1.2.5
	br3ttb/PID@^1.2.1
	thomasfredericks/Bounce2@^2.72
